export const ACTION_NAMES = {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    SET_USER: "SET_USER",
    AUTH_ERROR: "AUTH_ERROR",
    ADD_TODO: "ADD_TODO",
    FETCH_TODO: "FETCH_TODO",
    UPDATE_TODO: "UPDATE_TODO",
    DELETE_TODO: "DELETE_TODO"
}